# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='support_office',
        ),
        migrations.AddField(
            model_name='donor',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grants.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grants.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grants.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportoffice',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grants.Project'),
            preserve_default=False,
        ),
    ]
