# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grants', '0002_auto_20170519_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportoffice',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='support_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grants.SupportOffice'),
            preserve_default=False,
        ),
    ]
