# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grants', '0003_auto_20170519_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
