# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grants', '0004_auto_20170521_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grants.Donor'),
            preserve_default=False,
        ),
    ]
